### ISSUE TITLE
Source images from LocalStorage?

### ISSUE THREAD

**Issue by zuwuko** [orazz/flutter_images_slider#1]
I'm trying to display images from local storage instead of network and I'm getting this error:
The argument type 'Image' can't be assigned to the parameter type 'ImageProvider<dynamic>'.
`      ImagesSlider(
                      items: map<Widget>(imgList, (index, i) {
                        return Container(
                          decoration: BoxDecoration(
                              image: DecorationImage(
                                  image: Image.file(File(i)), // The argument type 'Image' can't be assigned to the parameter type 'ImageProvider<dynamic>'.
                                  fit: BoxFit.cover
                              )
                          ),
                        );
                      }),`

**Comment by orazz** [comment]
try this:
```
new Container(
  height: _yourHeight,
  width: _yourWidth,
  decoration: new BoxDecoration(
    image: new DecorationImage(
      image: new AssetImage('assets\\test.png'),
      fit: BoxFit.cover,
    ),
  ),
),
```

**Comment by zuwuko** [comment]
Works Perfect! I was coming back here to update I got it working and saw your reply with the same solution. Thank you.
